#! /bin/sh

xmodmap ~/.config/X11/.Xmodmap

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
bspwm &

# Monitors
# Either HDMI-A-0, DisplayPort-0, or DisplayPort-1
monitors=( $(xrandr | awk '$2 == "connected"{print $1}') )
num_monitors=${#monitors[@]}

# Flush monitors when before restarting
bspc config remove_unplugged_monitors true

internal_monitor=eDP
external_monitor=${monitors[-1]}

bspc monitor -d I II III IV V VI VII VIII IX

if [ $num_monitors -eq 1 ]
then
	bspc monitor $internal_monitor -d I II III IV V VI VII VIII IX
else
	# Move 3-9 desktops to external monitor
	for desktop in $(bspc query -D -m $internal_monitor | sed -n '3,9p')
	do
		bspc desktop $desktop --to-monitor $external_monitor

		# Not sure why BSPWM adds +1 index when sending a desktop to a different monitor.
		# So shift it to the previous desktop to maintain index from previous monitor
		bspc desktop $desktop -b prev
	done

	bspc monitor $internal_monitor -d I II
	bspc monitor $external_monitor -d III IV V VI VII VIII IX

	# FIXME: Reset monitor padding after sleep
	bspc config -m $external_monitor right_padding 0
	bspc config -m $external_monitor bottom_padding 0

	bspc wm -O $internal_monitor $external_monitor
fi

# Border
bspc config border_width 3
bspc config focused_border_color "#fca503"

# Gap
bspc config window_gap 5
bspc config top_padding -3

bspc config pointer_follows_focus true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  -2

bspc rule -a Brave-browser desktop='^4' focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a plasma.emojier state=floating
