#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &

# Monitor
bspc monitor eDP -d I
bspc monitor HDMI-A-0 -d II III IV V VI VII VIII IX

bspc wm -O eDP HDMI-A-0
bspc monitor HDMI-A-0

# Border
bspc config border_width 2
bspc config focused_border_color "#fca503"

# Gap
bspc config window_gap 10
bspc config top_padding 10

bspc config pointer_follows_focus true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave desktop='^3' focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
